/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ImplicationsRouteImport } from './routes/implications'
import { Route as FloorsRouteImport } from './routes/floors'
import { Route as EntropyRouteImport } from './routes/entropy'
import { Route as EastWestRouteImport } from './routes/east-west'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplicationsRoute = ImplicationsRouteImport.update({
  id: '/implications',
  path: '/implications',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorsRoute = FloorsRouteImport.update({
  id: '/floors',
  path: '/floors',
  getParentRoute: () => rootRouteImport,
} as any)
const EntropyRoute = EntropyRouteImport.update({
  id: '/entropy',
  path: '/entropy',
  getParentRoute: () => rootRouteImport,
} as any)
const EastWestRoute = EastWestRouteImport.update({
  id: '/east-west',
  path: '/east-west',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/east-west': typeof EastWestRoute
  '/entropy': typeof EntropyRoute
  '/floors': typeof FloorsRoute
  '/implications': typeof ImplicationsRoute
  '/industries': typeof IndustriesRoute
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/east-west': typeof EastWestRoute
  '/entropy': typeof EntropyRoute
  '/floors': typeof FloorsRoute
  '/implications': typeof ImplicationsRoute
  '/industries': typeof IndustriesRoute
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/east-west': typeof EastWestRoute
  '/entropy': typeof EntropyRoute
  '/floors': typeof FloorsRoute
  '/implications': typeof ImplicationsRoute
  '/industries': typeof IndustriesRoute
  '/map': typeof MapRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database'
    | '/east-west'
    | '/entropy'
    | '/floors'
    | '/implications'
    | '/industries'
    | '/map'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/database'
    | '/east-west'
    | '/entropy'
    | '/floors'
    | '/implications'
    | '/industries'
    | '/map'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/database'
    | '/east-west'
    | '/entropy'
    | '/floors'
    | '/implications'
    | '/industries'
    | '/map'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRoute
  EastWestRoute: typeof EastWestRoute
  EntropyRoute: typeof EntropyRoute
  FloorsRoute: typeof FloorsRoute
  ImplicationsRoute: typeof ImplicationsRoute
  IndustriesRoute: typeof IndustriesRoute
  MapRoute: typeof MapRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implications': {
      id: '/implications'
      path: '/implications'
      fullPath: '/implications'
      preLoaderRoute: typeof ImplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floors': {
      id: '/floors'
      path: '/floors'
      fullPath: '/floors'
      preLoaderRoute: typeof FloorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entropy': {
      id: '/entropy'
      path: '/entropy'
      fullPath: '/entropy'
      preLoaderRoute: typeof EntropyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/east-west': {
      id: '/east-west'
      path: '/east-west'
      fullPath: '/east-west'
      preLoaderRoute: typeof EastWestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRoute,
  EastWestRoute: EastWestRoute,
  EntropyRoute: EntropyRoute,
  FloorsRoute: FloorsRoute,
  ImplicationsRoute: ImplicationsRoute,
  IndustriesRoute: IndustriesRoute,
  MapRoute: MapRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
